#version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: ulongo-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ulongo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres:data

  redis:
    image: redis:alpine
    container_name: ulongo-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
